import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { execSync } from 'node:child_process';
import { readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { versionName } from './src/versionName.js';

// The build id is the commit, or the time when there is no git (CI always
// has git). It is baked into the bundle and written to version.json so the
// running app can notice a newer deploy (src/version.ts).
function buildId(): string {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim() || String(Date.now());
  } catch {
    return String(Date.now());
  }
}

function versionFile(id: string): Plugin {
  return {
    name: 'sora-version-json',
    generateBundle() {
      this.emitFile({ type: 'asset', fileName: 'version.json', source: JSON.stringify({ build: id, name: versionName(id) }) });
    },
  };
}

/** every file under public/, as paths relative to the site root */
function publicFiles(dir = 'public', prefix = ''): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...publicFiles(p, `${prefix}${name}/`));
    else out.push(`${prefix}${name}`);
  }
  return out;
}

/**
 * The service worker, written by the build so it knows every file of this
 * build: the bundle, the fonts, the icons. It keeps them in a cache named
 * after the build id, so a new deploy is a new cache and the old one is
 * dropped on activate. Hashed assets are served from the cache first (they
 * never change); everything else goes to the network first and falls back
 * to the cache, so version.json still finds a newer build when online and
 * the game still opens on a train.
 */
function serviceWorker(id: string, base: string): Plugin {
  return {
    name: 'sora-service-worker',
    apply: 'build',
    generateBundle(_opts, bundle) {
      if (!base.startsWith('/')) return;
      const built = Object.keys(bundle).filter((f) => f !== 'version.json' && !f.endsWith('.map'));
      const files = [base, ...[...built, ...publicFiles()].map((f) => base + f)];
      const sw = `// generated by vite.config.ts, build ${id}
const CACHE = 'sora-${id}';
const BASE = ${JSON.stringify(base)};
const PRECACHE = ${JSON.stringify(files)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const r = e.request;
  if (r.method !== 'GET') return;
  const url = new URL(r.url);
  if (url.origin !== location.origin || !url.pathname.startsWith(BASE)) return;
  const keep = (res) => {
    if (res && res.ok) caches.open(CACHE).then((c) => c.put(r, res.clone()));
    return res;
  };
  // module scripts send an Origin header and the cached copies carry Vary, so match without it
  const hit = (q) => caches.match(q, { ignoreSearch: true, ignoreVary: true });
  if (url.pathname.startsWith(BASE + 'assets/')) {
    e.respondWith(hit(r).then((h) => h || fetch(r).then(keep)));
    return;
  }
  e.respondWith(fetch(r).then(keep).catch(() => hit(r).then((h) => h || (r.mode === 'navigate' ? hit(BASE) : Response.error()))));
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: sw });
    },
  };
}

// GitHub Pages serves a project site under https://<user>.github.io/sora/,
// so production builds and `vite preview` use that base. Dev stays at '/'.
// `--mode portal` is the build for itch.io and Newgrounds: relative paths,
// because each portal serves the zip from its own folder.
export default defineConfig(({ command, isPreview, mode }) => {
  const id = buildId();
  const base = mode === 'portal' ? './' : command === 'build' || isPreview ? '/sora/' : '/';
  return {
    base,
    plugins: [react(), versionFile(id), serviceWorker(id, base)],
    define: { __BUILD__: JSON.stringify(id) },
    build: {
      rolldownOptions: {
        output: {
          codeSplitting: {
            groups: [{ name: 'react', test: /node_modules[\\/](react|react-dom|scheduler)[\\/]/ }],
          },
        },
      },
    },
  };
});
