import { L } from '../../i18n';
import type { CarDef } from '../types';

/**
 * The cars, one per class, slowest first. Numbers are the balance knobs;
 * the bot in tools/ reports what they do to a lap. The classes should be
 * a clear step apart with stock parts, and a fully built car of one class
 * should be close to a stock car of the next, so the choice at the dealer
 * is a real one. The career starts in the Tauno (docs/progression.md).
 * All four are the player's red; the body, the livery and the number
 * tell them apart. The footprint is real: the car model reads it, and
 * it climbs with the class (the ladder is in rivals.ts): the Tauno is a
 * tiny boxy old saloon, a Fiat 126 of a car.
 *
 * The first car of each class is the class car: the rivals' pace and the
 * licence targets are read off it (classCar()). After the four come the
 * dealer's wild buys, Hill Climb Racing's garage in a class's money: a
 * Niva and a Valmet tractor in C, a monster truck in B, a hearse in A.
 * Each handles like what it is, so the choice is a character, not a
 * faster number.
 */
export const CARS: CarDef[] = [
  {
    id: 'tauno',
    name: L('Tauno 2.0'),
    cls: 'JM',
    shape: 'saloon',
    price: 1200,
    blurb: L('Pieni kulmikas jokkisauto: takaveto, pehmeä ja väsynyt. Vuotaa öljyä, ja se on ainoa aseesi.', 'A tiny boxy folk-racing saloon: rear drive, soft and tired. It leaks oil, and that is your only weapon.'),
    accel: 13.5,
    topSpeed: 37,
    brake: 13,
    turnRate: 2.6,
    grip: 17,
    mass: 1.25,
    armour: 0,
    ram: 0,
    gun: 0,
    length: 2.9,
    width: 1.35,
    colour: '#c8352a',
    accent: '#e6dfcc',
    livery: 'roof',
    number: 7,
  },
  {
    id: 'kortteli',
    name: L('Kortteli 1.3'),
    cls: 'C',
    shape: 'hatch',
    price: 2500,
    blurb: L('Väsynyt kaupunkiauto soranastoilla. Kaikki alkaa tästä.', 'A tired town car on gravel tyres. Everyone starts here.'),
    accel: 18,
    topSpeed: 50.5,
    brake: 16,
    turnRate: 2.8,
    grip: 20,
    mass: 1,
    armour: 0,
    ram: 0,
    gun: 0,
    length: 3.7,
    width: 1.65,
    colour: '#c8352a',
    accent: '#e6dfcc',
    livery: 'band',
    number: 13,
  },
  {
    id: 'sorsa',
    name: L('Sorsa 1.6 GT'),
    cls: 'B',
    shape: 'coupe',
    price: 9000,
    blurb: L('Kevyt ja terävä. Ei anna anteeksi, mutta kääntyy.', 'Light and sharp. Unforgiving, but it turns.'),
    accel: 24.5,
    topSpeed: 60,
    brake: 19,
    turnRate: 3.0,
    grip: 23,
    mass: 0.95,
    armour: 0,
    ram: 0,
    gun: 0,
    length: 4.4,
    width: 1.75,
    colour: '#c8352a',
    accent: '#e6dfcc',
    livery: 'twin',
    number: 22,
  },
  {
    id: 'kiila',
    name: L('Kiila 4x4 Turbo'),
    cls: 'A',
    shape: 'rally',
    price: 28000,
    blurb: L('Neliveto ja turbo. Metsän kuningas.', 'Four-wheel drive and a turbo. King of the forest.'),
    accel: 28.5,
    topSpeed: 69.5,
    brake: 22,
    turnRate: 3.1,
    grip: 26,
    frontDrive: 0.3,
    mass: 1.25,
    armour: 0,
    ram: 0,
    gun: 0,
    length: 4.7,
    width: 1.9,
    colour: '#c8352a',
    accent: '#e8c040',
    livery: 'works',
    number: 1,
  },
  {
    id: 'niva',
    name: L('Niva 1.7 4x4'),
    cls: 'C',
    shape: 'niva',
    price: 3800,
    blurb: L('Korkea lyhyt laatikko, neliveto ja vararengas takaovessa. Pientare on sille tietä.', 'A tall short box, four-wheel drive and a spare on the back door. The verge is road to it.'),
    accel: 17,
    topSpeed: 47,
    brake: 15,
    turnRate: 2.9,
    grip: 19,
    frontDrive: 0.5,
    offroad: 0.65,
    mass: 1.15,
    armour: 0,
    ram: 0,
    gun: 0,
    length: 3.7,
    width: 1.7,
    colour: '#c8352a',
    accent: '#e6dfcc',
    livery: 'stripe',
    number: 4,
  },
  {
    id: 'valmet',
    name: L('Valmet 702'),
    cls: 'C',
    shape: 'tractor',
    price: 3200,
    blurb: L('Traktori. Suoralla kaikki menevät ohi, mutkassa se kääntyy paikallaan, ja kolarissa se jyrää kenet tahansa.', 'A tractor. Everyone passes it on a straight; it turns on the spot, and in a shunt it flattens anyone.'),
    accel: 21,
    topSpeed: 30.5,
    brake: 17,
    turnRate: 3.7,
    grip: 21,
    offroad: 0.85,
    mass: 2.6,
    armour: 0,
    ram: 0,
    gun: 0,
    length: 3.6,
    width: 1.9,
    colour: '#c8352a',
    accent: '#e6dfcc',
    livery: 'roof',
    number: 7,
  },
  {
    id: 'monsteri',
    name: L('Monsteri'),
    cls: 'B',
    shape: 'monster',
    price: 13500,
    blurb: L('Lava-auto renkailla, jotka ovat isompia kuin hytti. Pomppii, ja kenen päälle se tulee, se pyörähtää.', 'A pickup on tyres bigger than its cab. It bounces, and whoever it lands on spins.'),
    accel: 23.5,
    topSpeed: 56.5,
    brake: 16,
    turnRate: 2.8,
    grip: 21,
    frontDrive: 0.4,
    offroad: 0.6,
    spinOnShunt: true,
    mass: 2.1,
    armour: 0,
    ram: 0,
    gun: 0,
    length: 4.6,
    width: 2.6,
    colour: '#c8352a',
    accent: '#e8c040',
    livery: 'split',
    number: 88,
  },
  {
    id: 'ruumis',
    name: L('Ruumisauto'),
    cls: 'A',
    shape: 'hearse',
    price: 31000,
    blurb: L('Pitkä farmari lasiperällä, arkku ja seppele kyydissä. Nopea ja hiljainen, eikä kukaan halua sen eteen.', 'A long estate with a glass back, a coffin and a wreath aboard. Fast and quiet, and nobody wants to be in front of it.'),
    accel: 27.5,
    topSpeed: 73,
    brake: 21,
    turnRate: 2.9,
    grip: 25,
    mass: 1.4,
    armour: 0,
    ram: 0,
    gun: 0,
    length: 5.2,
    width: 1.8,
    colour: '#c8352a',
    accent: '#16130f',
    livery: 'band',
    number: 44,
  },
];

/** The class car: the first of its class, whose numbers the rivals race on. */
export function classCar(cls: CarDef['cls']): CarDef {
  return CARS.find((c) => c.cls === cls)!;
}

export const CAR_BY_ID: Record<string, CarDef> = Object.fromEntries(CARS.map((c) => [c.id, c]));
