// generated by vite.config.ts, build bbf5847
const CACHE = 'sora-bbf5847';
const BASE = "/sora/";
const PRECACHE = ["/sora/","/sora/grid2.js","/sora/apple-touch-icon.png","/sora/favicon-32.png","/sora/fonts/OFL.txt","/sora/fonts/big-shoulders-stencil.woff2","/sora/fonts/big-shoulders.woff2","/sora/icon-192.png","/sora/icon-512.png","/sora/icon.svg","/sora/manifest.webmanifest","/sora/t.gif","/sora/tracker.js"];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const r = e.request;
  if (r.method !== 'GET') return;
  const url = new URL(r.url);
  if (url.origin !== location.origin || !url.pathname.startsWith(BASE)) return;
  const keep = (res) => {
    if (res && res.ok) caches.open(CACHE).then((c) => c.put(r, res.clone()));
    return res;
  };
  // module scripts send an Origin header and the cached copies carry Vary, so match without it
  const hit = (q) => caches.match(q, { ignoreSearch: true, ignoreVary: true });
  if (url.pathname.startsWith(BASE + 'assets/')) {
    e.respondWith(hit(r).then((h) => h || fetch(r).then(keep)));
    return;
  }
  e.respondWith(fetch(r).then(keep).catch(() => hit(r).then((h) => h || (r.mode === 'navigate' ? hit(BASE) : Response.error()))));
});
